# Generated by Django 2.2.3 on 2019-07-15 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0002_cal_apply'),
    ]

    operations = [
        migrations.AddField(
            model_name='cal',
            name='cer',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cal',
            name='com',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
